set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER /tc/qt5/bin/gcc)
set(CMAKE_CXX_COMPILER /tc/qt5/bin/g++)
set(CMAKE_AR /usr/bin/arm-linux-gnueabihf-ar)
set(CMAKE_RANLIB /usr/bin/arm-linux-gnueabihf-ranlib)
set(CMAKE_OBJCOPY /usr/bin/arm-linux-gnueabihf-objcopy)
set(CMAKE_SYSROOT /tc/qt5/sysroot)
set(CMAKE_FIND_ROOT_PATH /tc/qt5/sysroot CACHE STRING "Target dependency roots")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_PREFIX_PATH /tc/qt5/sysroot/usr CACHE STRING "Target dependency prefixes")
